"""empty message

Revision ID: 50c45f31db0b
Revises: 0bbb89ebffc7
Create Date: 2025-09-29 20:28:15.021343

"""

from typing import Sequence, Union

import sqlalchemy as sa  # type: ignore

from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision: str = "50c45f31db0b"
down_revision: Union[str, Sequence[str], None] = "0bbb89ebffc7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("cards", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_cards_id"))

    op.drop_table("cards")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_email"))
        batch_op.drop_index(batch_op.f("ix_users_id"))

    op.drop_table("users")
    with op.batch_alter_table("user_cards", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_cards_id"))

    op.drop_table("user_cards")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_cards",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("user_id", sa.INTEGER(), nullable=True),
        sa.Column("card_id", sa.INTEGER(), nullable=True),
        sa.Column("progress_level", sa.INTEGER(), nullable=True),
        sa.Column("next_review_at", sa.DATETIME(), nullable=True),
        sa.ForeignKeyConstraint(
            ["card_id"],
            ["cards.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("user_cards", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_user_cards_id"), ["id"], unique=False)

    op.create_table(
        "users",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("email", sa.VARCHAR(), nullable=False),
        sa.Column("password", sa.VARCHAR(), nullable=False),
        sa.Column("created_at", sa.DATETIME(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_id"), ["id"], unique=False)
        batch_op.create_index(batch_op.f("ix_users_email"), ["email"], unique=1)

    op.create_table(
        "cards",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("question", sa.VARCHAR(), nullable=False),
        sa.Column("answer", sa.VARCHAR(length=1000), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("cards", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_cards_id"), ["id"], unique=False)

    # ### end Alembic commands ###
